version: "3.8"

services:
  smartwastemanagement-backend:
    build:
      context: "."
      dockerfile: "Dockerfile"
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - SW_db
    environment:
      DB_URL_DEV: ${DB_URL_DEV}
      DB_USERNAME_DEV: ${DB_USERNAME_DEV}
      DB_PASSWORD_DEV: ${DB_PASSWORD_DEV}

  SW_db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_DEV}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEV}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
